language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls"

# command to run tests
script: python manage.py test


after_success:
  - coverage run --source='.' manage.py test
  - coveralls


notifications:
  slack: aligot:b7YEBxUl9Edo1XLYOFBMZbPv
